### PR TITLE
user/apache-arrow: new package

### PR DESCRIPTION
**Pull request by a16bitsysop**
## Description
Describe what your pull request does here. For new packages, this is the
purpose of the package, for other changes this is what your change does,
for trivial package updates you may remove this.

## Checklist

Before this pull request is reviewed, certain conditions must be met.

The following must be true for all changes:

- [x] I have read [CONTRIBUTING.md](https://github.com/chimera-linux/cports/blob/master/CONTRIBUTING.md)

The following must be true for template/package changes:

- [x] I have read [Packaging.md](https://github.com/chimera-linux/cports/blob/master/Packaging.md#quality_requirements)
- [x] I have built and tested my changes on my machine

The following must be true for new package submissions:

- [x] I will take responsibility for my template and keep it up to date

### CODE REVIEW

File: user/apache-arrow/template.py [hunk 1]
```diff
@@ -0,0 +1,130 @@
...
+    "zlib-ng-compat-devel",
+    "zstd-devel",
+]
+checkdepends = ["bash"]
+pkgdesc = "Multi-language toolbox for fast data interchange and processing"
+license = "Apache-2.0"
+url = "https://arrow.apache.org"
+source = [
+    f"https://archive.apache.org/dist/arrow/arrow-{pkgver}/apache-arrow-{pkgver}.tar.gz",
+    f"https://github.com/microsoft/mimalloc/archive/v{_mimalloc_ver}.tar.gz",
```
Comment (q66) [inline user/apache-arrow/template.py:77]: why? just disable it

File: user/apache-arrow/template.py [hunk 2]
```diff
@@ -0,0 +1,130 @@
...
+    "-DARROW_WITH_ZSTD=ON",
+    "-DPARQUET_REQUIRE_ENCRYPTION=ON",
+    "-DLZ4_ROOT=/usr",
+]
+make_check_args = [
+    "-E",
+    "arrow-array-test|arrow-compute-scalar-temporal-test|arrow-utility-test|arrow-csv-test|arrow-ipc-json-simple-test|arrow-dataset-file-parquet-test",
+]
+make_check_env = {
+    "ARROW_TEST_DATA": f"/builddir/apache-arrow-{pkgver}/testing/data",
```
Comment (q66) [inline user/apache-arrow/template.py:44]: there is no guarantee these kind of paths will remain stable

self.chroot_cwd and do it from an appropriate `init_` hook

File: user/apache-arrow/template.py [hunk 3]
```diff
@@ -0,0 +1,130 @@
...
+    "pkgconf",
+]
+makedepends = [
+    "boost-devel",
+    "brotli-devel",
+    "glog-devel",
+    "grpc-devel",
+    "gtest-devel",
+    "libevent-devel",
+    "lz4",
```
Comment (q66) [inline user/apache-arrow/template.py:59]: that sounds like a hostdep?

Comment (q66) [reply user/apache-arrow/template.py:59]: (if at all)

File: user/apache-arrow/template.py [hunk 4]
```diff
@@ -0,0 +1,130 @@
...
+    case _:
+        configure_args += ["-DARROW_RUNTIME_SIMD_LEVEL=NONE"]
+
+
+@subpackage("apache-arrow-devel")
+def _(self):
+    return self.default_devel()
+
+
+@subpackage("libarrow")
```
Comment (q66) [inline user/apache-arrow/template.py:108]: subpackages that are not prefixed with the parent package name are not allowed

unless there is a good reason to split them all out, `apache-arrow-libs`

**Comment by q66** [comment]
given the can of worms grpc is, i suggest you submit that separately for separate review

File: user/apache-arrow/template.py (hunk 2 above)
Comment (a16bitsysop) [reply user/apache-arrow/template.py:44]: Okay will try that

File: user/apache-arrow/template.py (hunk 3 above)
Comment (a16bitsysop) [reply user/apache-arrow/template.py:59]: Ah it should be removed, added when I was trying to get it to find lz4. It needs path set later on to find it.

**Comment by a16bitsysop** [comment]
Okay will split out into another pull request

**Comment by a16bitsysop** [comment]
left grpc in temporarily so it still builds, I can't get init_check setting variables to work and trying to use warn to output the path gives `AttributeError: 'Logger' object has no attribute 'warn'`

Left in latest commit to show

File: user/apache-arrow/template.py [hunk 5]
```diff
@@ -0,0 +1,104 @@
...
+    case "aarch64" | "x86_64":
+        configure_args += ["-DARROW_RUNTIME_SIMD_LEVEL=MAX"]
+        makedepends += ["xsimd"]
+    case _:
+        configure_args += ["-DARROW_RUNTIME_SIMD_LEVEL=NONE"]
+
+
+def init_check(self):
+    self.logger.warn(f"{self.chroot_cwd}/arrow-testing/data")
+    make_check_env = {
```
Comment (q66) [inline user/apache-arrow/template.py:96]:
```
    self.make_check_env["ARROW_TEST_DATA"] = ...
    self.make_check_env["PARQUET_TEST_DATA"] = ...
```

Comment (q66) [reply user/apache-arrow/template.py:96]: also, `= str(self.chroot_cwd / "arrow-testing/data")` and so on

**Comment by q66** [comment]
i tried updating this but can't get it to support any less than sse4.2 compile-time baseline (it fails to build because it expects `xsimd::batch<signed char, xsimd::sse4_2>::size` to be at least 16 at compile time which is only true when the whole thing is build with `-msse4.2`, which we can't do, even though it seems to have some form of runtime dispatch)

feel free to figure it out and update it if you're still interested in it, i'll close it for now

other than that i have some minor nits with the template but i can fix them myself when it comes down to it
